//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Dev\\")]
        public string RepoLocation {
            get {
                return ((string)(this["RepoLocation"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gulp 07-Copy-App")]
        public string CopyAppFilesComand {
            get {
                return ((string)(this["CopyAppFilesComand"]));
            }
            set {
                this["CopyAppFilesComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gulp 03-Publish-All-Projects")]
        public string PublishAllProjectsComand {
            get {
                return ((string)(this["PublishAllProjectsComand"]));
            }
            set {
                this["PublishAllProjectsComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gulp Build-Solution")]
        public string BuildSolutionComand {
            get {
                return ((string)(this["BuildSolutionComand"]));
            }
            set {
                this["BuildSolutionComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gulp Publish-Foundation-Projects")]
        public string PublishFoundationProjectsComand {
            get {
                return ((string)(this["PublishFoundationProjectsComand"]));
            }
            set {
                this["PublishFoundationProjectsComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gulp Publish-Feature-Projects")]
        public string PublishFeatureProjectsComand {
            get {
                return ((string)(this["PublishFeatureProjectsComand"]));
            }
            set {
                this["PublishFeatureProjectsComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gulp Publish-Project-Projects")]
        public string PublishProjectProjectsComand {
            get {
                return ((string)(this["PublishProjectProjectsComand"]));
            }
            set {
                this["PublishProjectProjectsComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gulp 04-Apply-Xml-Transform")]
        public string ApplyXmlTransformComand {
            get {
                return ((string)(this["ApplyXmlTransformComand"]));
            }
            set {
                this["ApplyXmlTransformComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gulp 05-Sync-Unicorn")]
        public string SyncUnicornComand {
            get {
                return ((string)(this["SyncUnicornComand"]));
            }
            set {
                this["SyncUnicornComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/Users/kuzminv-s/AppData/Local/Programs/Git/git-cmd.exe")]
        public string GitBashPath {
            get {
                return ((string)(this["GitBashPath"]));
            }
            set {
                this["GitBashPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("npm run build")]
        public string BuildComand {
            get {
                return ((string)(this["BuildComand"]));
            }
            set {
                this["BuildComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/Users/kuzminv-s/AppData/Local/Programs/Git/git-cmd.exe")]
        public string CmdPath {
            get {
                return ((string)(this["CmdPath"]));
            }
            set {
                this["CmdPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double WindowTop {
            get {
                return ((double)(this["WindowTop"]));
            }
            set {
                this["WindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double WindowLeft {
            get {
                return ((double)(this["WindowLeft"]));
            }
            set {
                this["WindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double WindowHeight {
            get {
                return ((double)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState WindowState {
            get {
                return ((global::System.Windows.WindowState)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double WindowWidth {
            get {
                return ((double)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CI-Clean")]
        public string CICleanComand {
            get {
                return ((string)(this["CICleanComand"]));
            }
            set {
                this["CICleanComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Publish-Foundation-Projects")]
        public string CIPublishFoundationComand {
            get {
                return ((string)(this["CIPublishFoundationComand"]));
            }
            set {
                this["CIPublishFoundationComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Publish-Feature-Projects")]
        public string CIPublishFeatureComand {
            get {
                return ((string)(this["CIPublishFeatureComand"]));
            }
            set {
                this["CIPublishFeatureComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Publish-Project-Projects")]
        public string CIPublishProjectComand {
            get {
                return ((string)(this["CIPublishProjectComand"]));
            }
            set {
                this["CIPublishProjectComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gulp {0} --gulpfile gulpfile-ci.js")]
        public string CICommandBase {
            get {
                return ((string)(this["CICommandBase"]));
            }
            set {
                this["CICommandBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CI-And-Prepare-Files-DEV")]
        public string CIDevComand {
            get {
                return ((string)(this["CIDevComand"]));
            }
            set {
                this["CIDevComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CI-And-Prepare-Files-UAT")]
        public string CIUatComand {
            get {
                return ((string)(this["CIUatComand"]));
            }
            set {
                this["CIUatComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CI-And-Prepare-Files-PROD")]
        public string CIProdComand {
            get {
                return ((string)(this["CIProdComand"]));
            }
            set {
                this["CIProdComand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Feature, Foundation, Project")]
        public string SrcMainFolders {
            get {
                return ((string)(this["SrcMainFolders"]));
            }
            set {
                this["SrcMainFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gulp Publish-Project -m {0}")]
        public string PublishProjectCommand {
            get {
                return ((string)(this["PublishProjectCommand"]));
            }
            set {
                this["PublishProjectCommand"] = value;
            }
        }
    }
}
